/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "atracker"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "atracker"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0.1"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * output_arg;	/**< @brief output directory (default='.').  */
  char * output_orig;	/**< @brief output directory original value given at command line.  */
  const char *output_help; /**< @brief output directory help description.  */
  char * fout_suffix_arg;	/**< @brief additional suffix for the resulting output files.  */
  char * fout_suffix_orig;	/**< @brief additional suffix for the resulting output files original value given at command line.  */
  const char *fout_suffix_help; /**< @brief additional suffix for the resulting output files help description.  */
  char * model_arg;	/**< @brief path to the object detector (PyTorch ML model).  */
  char * model_orig;	/**< @brief path to the object detector (PyTorch ML model) original value given at command line.  */
  const char *model_help; /**< @brief path to the object detector (PyTorch ML model) help description.  */
  int ant_length_arg;	/**< @brief expected ant length (default='80').  */
  char * ant_length_orig;	/**< @brief expected ant length original value given at command line.  */
  const char *ant_length_help; /**< @brief expected ant length help description.  */
  float confidence_arg;	/**< @brief confidence threshold for the calling object detector model, typically [0.25, 0.85] for a YOLOv5-based model (default='0.32').  */
  char * confidence_orig;	/**< @brief confidence threshold for the calling object detector model, typically [0.25, 0.85] for a YOLOv5-based model original value given at command line.  */
  const char *confidence_help; /**< @brief confidence threshold for the calling object detector model, typically [0.25, 0.85] for a YOLOv5-based model help description.  */
  float rescale_arg;	/**< @brief extend and rescale canvas of the input frames to ensure the expected size of ants E (0, 1). NOTE: causes a computational overhead without affecting original coordinates (default='1').  */
  char * rescale_orig;	/**< @brief extend and rescale canvas of the input frames to ensure the expected size of ants E (0, 1). NOTE: causes a computational overhead without affecting original coordinates original value given at command line.  */
  const char *rescale_help; /**< @brief extend and rescale canvas of the input frames to ensure the expected size of ants E (0, 1). NOTE: causes a computational overhead without affecting original coordinates help description.  */
  int cuda_flag;	/**< @brief computational device for the object detector (CUDA GPU or CPU} (default=off).  */
  const char *cuda_help; /**< @brief computational device for the object detector (CUDA GPU or CPU} help description.  */
  char * img_arg;	/**< @brief path to the input image.  */
  char * img_orig;	/**< @brief path to the input image original value given at command line.  */
  const char *img_help; /**< @brief path to the input image help description.  */
  char * video_arg;	/**< @brief path to the input video.  */
  char * video_orig;	/**< @brief path to the input video original value given at command line.  */
  const char *video_help; /**< @brief path to the input video help description.  */
  int frame_start_arg;	/**< @brief start frame index (default='0').  */
  char * frame_start_orig;	/**< @brief start frame index original value given at command line.  */
  const char *frame_start_help; /**< @brief start frame index help description.  */
  int frame_num_arg;	/**< @brief the number of frames (default='-1').  */
  char * frame_num_orig;	/**< @brief the number of frames original value given at command line.  */
  const char *frame_num_help; /**< @brief the number of frames help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int output_given ;	/**< @brief Whether output was given.  */
  unsigned int fout_suffix_given ;	/**< @brief Whether fout_suffix was given.  */
  unsigned int model_given ;	/**< @brief Whether model was given.  */
  unsigned int ant_length_given ;	/**< @brief Whether ant-length was given.  */
  unsigned int confidence_given ;	/**< @brief Whether confidence was given.  */
  unsigned int rescale_given ;	/**< @brief Whether rescale was given.  */
  unsigned int cuda_given ;	/**< @brief Whether cuda was given.  */
  unsigned int img_given ;	/**< @brief Whether img was given.  */
  unsigned int video_given ;	/**< @brief Whether video was given.  */
  unsigned int frame_start_given ;	/**< @brief Whether frame_start was given.  */
  unsigned int frame_num_given ;	/**< @brief Whether frame_num was given.  */

  int detection_group_counter; /**< @brief Counter for group detection */
  int input_group_counter; /**< @brief Counter for group input */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
